### ISSUE TITLE
Date and Location

### ISSUE THREAD

**Issue by RichardLitt** [nodeschool/chiang-mai#1]
I was thinking Friday, May 1st at Bibie. Bibe is on Niman and can host around 25 people, and they already said that they'd be open to us going there. What do you guys think? 

Timing-wise, maybe 3-6pm? 

We could follow it up with dinner somewhere local.

**Comment by RichardLitt** [comment]
Ok, I went to Punspace, and they should have a space for 30 people. Contacting them now via email, the event person wasn't in.

**Comment by rburns** [comment]
To get listed on the nodeschool.io calendar http://nodeschool.io/events.html an issue should be filed here https://github.com/nodeschool/organizers/issues/new

**Comment by RichardLitt** [comment]
Already listed there. I need to edit the date though, opened [this issue](https://github.com/nodeschool/organizers/issues/199).

**Comment by RichardLitt** [comment]
Set as May 1st, Friday, from 3pm-6pm, at Punspace Tha Phae Gate.
