### ISSUE TITLE
Create FB Event

### ISSUE THREAD

**Issue by RichardLitt** [nodeschool/chiang-mai#10]
And then share if on Chiang Mai groups

**Comment by alvinsj** [comment]
maybe using punspace account? @vsirisanthana

**Comment by vsirisanthana** [comment]
@alvinsj @RichardLitt We can do that, if you'd like.

**Comment by RichardLitt** [comment]
@vsirisanthana That would be great! We have a logo here, if you need one: https://github.com/nodeschool/chiang-mai/blob/gh-pages/images/nodeschool-cnx.svg

**Comment by RichardLitt** [comment]
Let me know how I can help. Copy?

**Comment by RichardLitt** [comment]
> NodeSchool is a community event for learning nodejs. Node is the premier back-end framework for JS, the most popular language for developers at the moment. If you're just starting out, or if you're interested in learning about ES6 compilers, we welcome you and ask you to join us at an event for a few hours of undirected learning and hacking away.
> 
> This free community event is a set of do-it-yourself open source workshops created by the community, for the community. After installing you can step through the lessons for each topic at your own pace, learning how to use node.js, npm and other related tools by writing code to solve realistic problems. It is a great incentive to work through the workshops with fellow local developers, sharing advice if you're ever stuck or are curious about alternative solutions.

**Comment by RichardLitt** [comment]
Sweet! https://www.facebook.com/events/1631984310371660/

**Comment by RichardLitt** [comment]
Added to website.
