### ISSUE TITLE
Mentors

### ISSUE THREAD

**Issue by RichardLitt** [nodeschool/chiang-mai#11]
Who is interested in being a mentor?

**Comment by radiofrequency** [comment]
I checked out the electives and I can help people with a few of them.

**Comment by RichardLitt** [comment]
@radiofrequency Awesome!

**Comment by dvdbng** [comment]
Me!

**Comment by RichardLitt** [comment]
:palm_tree: :palm_tree: :palm_tree:

**Comment by ghost** [comment]
I'm in.

**Comment by rburns** [comment]
I can help. Probably most useful for the core workshoppers.

**Comment by RichardLitt** [comment]
:+1:!
