### ISSUE TITLE
NodeSchool International Day (23rd May 2015)

### ISSUE THREAD

**Issue by alvinsj** [nodeschool/chiang-mai#15]
http://nodeschool.io/international-day/

kind of addicted lol. should we do this too?
@RichardLitt @kytwb @YouWoTMA @radiofrequency @soyjavi @nazt @rburns
will you guys still be around?

**Comment by ghost** [comment]
I'll be around, let's see if we have more feedback from the others.

**Comment by RichardLitt** [comment]
I don't think I'll be here. But I do have stickers you can use. :)

**Comment by soyjavi** [comment]
I’ll be here :)

—
Javi Jiménez Villar
@soyjavi

**Comment by dvdbng** [comment]
I'll be here too, glad to help :)

**Comment by rburns** [comment]
I'll be here, and glad to help

**Comment by ghost** [comment]
Hey guys, looks like we need to wrap it up quickly if we wanna be in :-) We need to find a place to host; sending a message to Punspace right now. Alternative ideas welcome in case Punspace can't this time.
_Edit:_ Email sent, will keep you posted, hoping I hear back from them tomorrow.

**Comment by rburns** [comment]
if numbers were smaller, I can think of a few other places. but unsure of anywhere that accommodates 30 or so people sitting down coding more comfortably than punspace tha pae

**Comment by jengguru** [comment]
wooohoo! many interesting things are coming :+1: ^___^

**Comment by ghost** [comment]
It's happening! We got a go from Punspace :+1: 
[Website](http://nodeschool.io/chiang-mai) has been updated and event created on [Facebook](https://www.facebook.com/events/493163420832014/)
Spread the word! :100:

**Comment by RichardLitt** [comment]
:+1: That's awesome!

**Comment by ghost** [comment]
![https://lh4.googleusercontent.com/-EpIRTPNPvj8/VWGU3tGVRII/AAAAAAAANzU/zcrzdjuyuSE/w971-h546-no/20150523_154825.jpg](https://lh4.googleusercontent.com/-EpIRTPNPvj8/VWGU3tGVRII/AAAAAAAANzU/zcrzdjuyuSE/w971-h546-no/20150523_154825.jpg)
![https://lh4.googleusercontent.com/-p35bPhnZhUM/VWGUv-b4hUI/AAAAAAAANyw/etz7RdiOb_U/w971-h546-no/20150523_154731.jpg](https://lh4.googleusercontent.com/-p35bPhnZhUM/VWGUv-b4hUI/AAAAAAAANyw/etz7RdiOb_U/w971-h546-no/20150523_154731.jpg)
![https://lh4.googleusercontent.com/-d8rykWqrVzg/VWGVcqKIMdI/AAAAAAAAN18/1IrevZ_oV1s/w971-h546-no/20150523_163901.jpg](https://lh4.googleusercontent.com/-d8rykWqrVzg/VWGVcqKIMdI/AAAAAAAAN18/1IrevZ_oV1s/w971-h546-no/20150523_163901.jpg)
![https://lh6.googleusercontent.com/-8t6yWhAUOcE/VWGVNiLG9tI/AAAAAAAAN00/GuytPBmPcU0/w971-h546-no/20150523_163643.jpg](https://lh6.googleusercontent.com/-8t6yWhAUOcE/VWGVNiLG9tI/AAAAAAAAN00/GuytPBmPcU0/w971-h546-no/20150523_163643.jpg)
![https://lh4.googleusercontent.com/-BO7wHpc-kPA/VWGV5VJhoqI/AAAAAAAAN4Q/LREjuaM0CBw/w971-h546-no/20150523_171558.jpg](https://lh4.googleusercontent.com/-BO7wHpc-kPA/VWGV5VJhoqI/AAAAAAAAN4Q/LREjuaM0CBw/w971-h546-no/20150523_171558.jpg)
![https://lh4.googleusercontent.com/-9X84CpSPWYM/VWGVgzW1QrI/AAAAAAAAN2U/QSYf8PJxUjw/w971-h546-no/20150523_163918.jpg](https://lh4.googleusercontent.com/-9X84CpSPWYM/VWGVgzW1QrI/AAAAAAAAN2U/QSYf8PJxUjw/w971-h546-no/20150523_163918.jpg)
