### ISSUE TITLE
Fork reset to nailbrain/chaing-mai

### ISSUE THREAD

**Issue by RichardLitt** [nodeschool/chiang-mai#17]
In case anyone is curious, refer to: https://github.com/nodeschool/organizers/issues/248

Who is the main organizer, at the moment? Let me know and I can make sure you're in the new nodeschool/chapter-organizers group.

**Comment by ghost** [comment]
No main organizer for now, see #18

**Comment by RichardLitt** [comment]
Cool. This issue no longer relevant since the reset was fixed.
