### ISSUE TITLE
What about an event end of March?

### ISSUE THREAD

**Issue by mattiaerre** [nodeschool/chiang-mai#19]
# Description

Hello friends, I'll be in Chiang Mai from Saturday (03/03) until the end of March and I'd really love to attend/help to organize a nodeschool event there; anyone that's interested? Who should I be reaching out to? Who should I be talking to?

**Comment by mattiaerre** [comment]
I may need your help my dear friends 😎 @Xabadu @tlhunter @nebrius

**Comment by tlhunter** [comment]
Looks like there aren't any tech Meetups for which to find possible locals:
https://www.meetup.com/cities/th/chiang_mai/events/

**Comment by tlhunter** [comment]
I know the location is mentioned a lot amongst Digital Nomads:
https://www.reddit.com/r/digitalnomad/

Maybe post something in here:
https://www.reddit.com/r/chiangmai/

As far as making an official Nodeschool event, try to reach out to the folks who have created/closed issues in this repo.

**Comment by mattiaerre** [comment]
thanks so much @tlhunter will try what you are suggesting

**Comment by RichardLitt** [comment]
I set up the last one, but I don't have that much advice. I used Hacker Paradise members to bootstrap the initial members, and then I also reached out on NomadList and to other nomads I knew in the city. I went to each of the coworking stations and asked about a place to host, and about advertising. We had a pretty good turn out.

**Comment by mattiaerre** [comment]
closing because this is happening 😄 #20
