### ISSUE TITLE
Mentor Registration for March 24th, 2018

### ISSUE THREAD

**Issue by mattiaerre** [nodeschool/chiang-mai#20]
Hello everybody 👋!

[The Brick Plus](https://goo.gl/maps/k4cJxAjdkx52) is hosting us on March 24th from 1:00PM - 5:00PM. The address is: **Su Thep, Mueang Chiang Mai District, Chiang Mai 50200**

Comment to get involved or ask questions. If this is your first time mentoring and are in doubt, we're sure you can! Just leave us a comment and we'll help you in any way we can.

Mentors should:

- Have already completed the [core NodeSchool workshoppers](https://nodeschool.io/#workshopper-list) before the event.
- Having also completed elective workshoppers is a great bonus.
- Review the [Mentor Best Practices](https://github.com/nodeschool/organizers/wiki/Event-Mentor-Best-Practices) wiki page.
- Arrive 30 minutes early (12:30PM) so we can get setup and have our mentor meeting.

Confirmed mentors:

- [X] @Nikhil22
- [X] @blairexico
- [X] @eversionsystems
- [ ] You?
- [ ] You?
- [ ] You?
- [ ] You?
- [ ] You?
- [ ] You?
- [ ] You?

Organizers:

- [X] @mattiaerre

Thanks for joining! 🙌

Attendee registration link: [https://www.meetup.com/NodeSchool-CM/events/248602547/](https://www.meetup.com/NodeSchool-CM/events/248602547/)

**Comment by mattiaerre** [comment]
@Nikhil22 @blairexico @joshuazmiller 👍 ? 🍕 ? 😎 ?

**Comment by Nikhil22** [comment]
I'm down to mentor.

**Comment by mattiaerre** [comment]
this is fantastic, thanks @Nikhil22

**Comment by waxmenow** [comment]
I will be there to mentor!

**Comment by blairexico** [comment]
I will be there to mentor! Looking forward

**Comment by mattiaerre** [comment]
thanks so much @blairexico the mentor's list has been updated

**Comment by eversionsystems** [comment]
I'll give mentoring a crack :)

**Comment by mattiaerre** [comment]
awesome! thank you @eversionsystems and see you Saturday!

**Comment by mattiaerre** [comment]
that event was a blast! thanks so much mentors; w/o your help this wouldn't have been possible kudos to @Nikhil22 @blairexico and @eversionsystems I hope you enjoyed!
