### ISSUE TITLE
Stickers

### ISSUE THREAD

**Issue by RichardLitt** [nodeschool/chiang-mai#5]
We should get some stickers up in here. Anyone know where we could order hexagonal stickers // know a graphic designer? 

Examples in Hanoi:
https://github.com/nodeschool/hanoi/issues/2#issuecomment-94615075

**Comment by ghost** [comment]
![NodeSchool CNX](http://i.imgur.com/sQrplci.png)

I know there's an app to make basic nodeschool stickers: [click here](http://www.finnpauls.de/nodeschool-stickerify/). And [here](https://github.com/nodeschool/nodeschool.github.io/tree/master/images/make-a-sticker) there's the illustrator source if we wanna change the building inside with an elephant or something.

**Comment by RichardLitt** [comment]
That's awesome! Want to just use that? We need to find a sticker maker around here.

**Comment by ghost** [comment]
LGTM, unless someone come with something more customized from the AI source file or a better palette.

**Comment by RichardLitt** [comment]
Anyone want to try hitting up these sticker shops this week? http://www.thaivisa.com/forum/topic/616700-stickers-printing-shop/

**Comment by alvinsj** [comment]
I just sent an email to a contact I found, checking whether they are able to do it on time.

**Comment by RichardLitt** [comment]
:+1: I asked on the Chiang Mai nomads facebook group, too.

**Comment by alvinsj** [comment]
The dimension, if anyone need it. https://github.com/terinjokes/StickerConstructorSpec/issues/8

**Comment by RichardLitt** [comment]
I've got a few recs for Kid Scan Kaew (might be Kad Suan Kuew?): "I use the place on the 1st floor at the back. After 2 years here they now do all my stickers, posters pvc signs, t-shirts etc." I'll be back in town tomorrow night, but if anyone could check earlier?

**Comment by ghost** [comment]
I'll go check this afternoon.

**Comment by alvinsj** [comment]
didn't get any reply still, we should just proceed with the ksk one.

**Comment by ghost** [comment]
Didn't find the sticker shop at KSK, might try again tomorrow (I was there in a rush).

**Comment by RichardLitt** [comment]
Cool. Keep us updated, and thanks for helping out!

**Comment by ghost** [comment]
Looks like we won't have stickers for this edition :( Next one!

**Comment by RichardLitt** [comment]
Happens :) I might make some just for me at some point :P

—

**Comment by ghost** [comment]
If you happen to do them in CNX, let me know where about.

**Comment by alvinsj** [comment]
yea we can still do it next time ;)

**Comment by RichardLitt** [comment]
The place was here: 18.796523, 98.984496

It was hella cheap. I don't know the Thai name.

**Comment by ghost** [comment]
Awesome! :+1:

**Comment by alvinsj** [comment]
awesome, you made it! Thank you @RichardLitt 
![alvinsj_2015-may-01](https://cloud.githubusercontent.com/assets/243186/7430940/5dbc8ff0-f043-11e4-9cc7-0ee9ab87f955.jpg)
