### ISSUE TITLE
Attendance Sheet

### ISSUE THREAD

**Issue by RichardLitt** [nodeschool/chiang-mai#6]
_Please add a note here saying you are coming so that we have some idea of attendance. :) Thanks!_

I am coming!

**Comment by radiofrequency** [comment]
i'll be coming +5

**Comment by RichardLitt** [comment]
So... you're bringing five people? :)

**Comment by radiofrequency** [comment]
yup

**Comment by RichardLitt** [comment]
Nice!

**Comment by rdoc101** [comment]
Hi, just saw this event posted by @cnxtech. Looks pretty cool, so +1 for me

**Comment by ciaranmag** [comment]
Yeah I'll be there

**Comment by ghost** [comment]
I'll be here.

**Comment by alvinsj** [comment]
I'm coming

**Comment by magalhini** [comment]
Aye, sir!

**Comment by bradonomics** [comment]
I would love to attend, but I fear my lack of JavaScript knowledge will frustrate the organizers. How much JS is needed for this to be beneficial?

**Comment by rburns** [comment]
@bradonomics there are some entry level modules http://nodeschool.io/#workshopper-list (core) as well as some more involved topics (electives) I would think little no prior experience is necessary for the core workshoppers.

**Comment by RichardLitt** [comment]
@bradonomics There's even a workshopper for people with no programming experience: https://www.github.com/sethvincent/javascripting. Come along!

**Comment by samber** [comment]
Coming too

**Comment by jerriep** [comment]
Sounds like a fun way to spend a day off... :) I'm in

**Comment by bradonomics** [comment]
@rburns @RichardLitt Cheers guys, I'll poke at these tutorials and see you on Friday.

**Comment by RichardLitt** [comment]
@bradonomics If you need help poking, just wait until Friday - NodeSchool is pretty chill, it is basically only people in a room working on the workshoppers together. If you've got questions, we're there for you, but there's no specific guided learning.

**Comment by altninja** [comment]
:D

**Comment by rburns** [comment]
+1

**Comment by nazt** [comment]
+1 I will go.

**Comment by bathrozen** [comment]
+1

**Comment by andymaule** [comment]
+1

**Comment by aimmango** [comment]
+1

**Comment by amna** [comment]
+1

**Comment by RichardLitt** [comment]
<3 to all of you. Looking forward to this!

**Comment by microHub** [comment]
I'll be there +1

**Comment by myzenon** [comment]
+1

**Comment by qoopooh** [comment]
+1

**Comment by armno** [comment]
+1 :+1:

**Comment by moviendome** [comment]
+1

**Comment by phusananwan** [comment]
+1

**Comment by RichardLitt** [comment]
Thanks all! Glad you're here.
